### ISSUE TITLE
Enums: Document that out-of-range values for fieldless repr(C) enums are UB

### ISSUE THREAD

**Issue by sdroege** [rust-lang/unsafe-code-guidelines#137]
See https://github.com/nikomatsakis/rust-memory-model/issues/41

**Comment by RalfJung** [comment]
This is basically subsumed by https://github.com/rust-lang/unsafe-code-guidelines/issues/69: any enum value must have a valid discriminant value.

**Comment by sdroege** [comment]
It is, but I believe it would be useful to document this explicitly for `repr(C)` enums in addition to documenting it in general for all types of enums. I.e. that the attribute only affects the representation (the in memory representation is the same as in C), and that it does **not** cause the enum to behave like the same enum in C (being a fancy integer that can take any possible value, not just the ones defined as part of the enum).

This is something that I noticed being misunderstood by quite a few people in the past (including myself), who believed that `repr(C)` makes the enum be equivalent in all regards to the same enum in C. When passing via FFI this misunderstanding can easily lead to UB, and the correct solution would be to pass plain integers via FFI instead, checking on the Rust side if it's a valid value and then converting to an enum.

**Comment by RalfJung** [comment]
I agree. Please leave that note in the other discussion. :)

**Comment by sdroege** [comment]
Done, thanks :)
