### ISSUE TITLE
A Formal C Memory Model Supporting Integer-Pointer Casts

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/unsafe-code-guidelines#143]
Links: [PDF](http://www.cis.upenn.edu/~stevez/papers/KHM+15.pdf), [ACM](http://dl.acm.org/citation.cfm?id=2738005&CFID=670466241&CFTOKEN=40913229)

This is a memory model targeting C. The C specification itself has very loose rules that don't support a lot of common things people do in C programs, primarily around using pointers as integers (e.g., bitmasking, etc). 

The key ideas of the model are as follows:
- When you allocate memory, it is initially assigned a _logical_ identifier and (conceptually) has no physical address (yet).
- Once a pointer is cast to an integer, the memory block it points at is assigned a physical address.
- Once a memory block has a physical address, then it is much less optimizable. For example, if you cast from an integer `i` to a pointer `p`, you have to assume that accesses through `p` could affect any block with a physical address, but you know they can't affect anything that doesn't have a physical address.

Some examples from the paper:
### Keeping local variables private (supported)

Consider this question:

``` C
int f() {
  int a = 0;
  g(); // Can `g()` observe/affect value of `a`?
  return a;
}
```

In this model, the answer is no: the allocation of `a` is private, and at no point did the code do something like `(int) &a` to convert it into a concrete block.
### Keeping local allocations private (supported)

Consider this question:

``` C
p = malloc();
*p = 123;
bar(); // Can this affect `*p`?
a = *p;
hash_put(h, p, a);
```

In this model, the answer is no: the allocation of `p` is private, and at no point did the code do something like `(int) p` to convert it into a concrete block.

The paper calls this "ownership transfer". I've avoided this term because it's so different from what Rust means by this term. It's more like "retaining" or "respecting" ownership (of `p`).

The paper says that `clang -O2` does this kind of optimization, but not `gcc -O2`, and claims therefore that it may not be that important.
### Dead Cast Elimination (unsupported in the model)

Consider this question (not from paper):

``` C
foo(int *p) {
    int x = (int) p; // Can we drop this unused value?
    println("%d", *p);
}
```

In this model, we cannot eliminate `(int) p` even if the result is not used because it has a side-effect of (potentially) assigning `p` a concrete value.

The paper addresses this by doing this optimization later in the pipeline. Basically at the point where we drop this model and convert to something more concrete. 
### Example limitation

Here is an example of an optimization prohibited by this approach.

``` C
p = malloc(1);
*p = 123;
b = (int) p;
bar();
a = *p;
hash_put(h, b, a); // Can we optimize this to `hash_put(h, b, 123)`?
```

The answer is no: `p` was made "concrete", and hence may be affected by `bar()`.  Interestingly, a slight reordering _would_ enable the optimization:

``` C
p = malloc(1);
*p = 123;
bar(); // `p` is not concrete **yet**...
b = (int) p;
a = *p;
hash_put(h, b, a); // ...hence no opportunity between cast and here to modify `*p`
```

**Comment by JakobDegen** [comment]
Discussed in backlog bonanza - closing. Memory models have evolved a lot since 2016, it's not clear that this issue brings a lot of value
