### ISSUE TITLE
Collection of assumptions about MIR semantics

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#150]
Let's use this issue to collect assumptions that rustc is making about MIR semantics. Usually those assumptions occur as an optimization.

* https://github.com/rust-lang/rust/pull/60187 assumes that after a `StorageDead`+`StorageLive`, the address of a local is allowed to differ -- so old pointers (created before the `StorageDead`) may not be used any more. Cc https://github.com/rust-lang/unsafe-code-guidelines/issues/129
* https://github.com/rust-lang/rust/pull/61922 assumes that if the address of a local has not been taken, after moving out there is just no way to access that storage again. It can't be accessed through existing pointers because none have been created, and new pointers cannot be created because the move checker would prevent that.

**Comment by RalfJung** [comment]
I feel for issues such as this, a wiki is a better fit. Do we want to use the wiki of this project for that?

**Comment by Lokathor** [comment]
Well, "yes that sounds good, but maybe wait until there's more than 2 bullet points"

**Comment by JakobDegen** [comment]
Closing for backlog bonanza. Issue has had no updates since 2019. If someone wants to actually maintain a list of these things, feel free to open a new issue
