### ISSUE TITLE
Layout: Separate chapter on layout stability

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#151]
Currently there is some discussion of layout stability in https://github.com/rust-lang/unsafe-code-guidelines/blob/97cbda4bd9f4e5de60a695a0d0bc1862f638ea24/reference/src/layout/structs-and-tuples.md. But that seems like the wrong place; this applies not just to structs but is a general layout concern. We should IMO have a chapter that talks about layout in general, defines it (or rather links to the glossary for that), and discussed some over-arching concerns --such as stability.

**Comment by gnzlbg** [comment]
> We should IMO have a chapter that talks about layout in general, defines it (or rather links to the glossary for that), and discussed some over-arching concerns --such as stability.

We can probably use the main page of the layout chapter for that.

**Comment by JakobDegen** [comment]
Closing, like most editorial issues. This is probably a good idea but irrelevant since the repo content is unmaintained anyway
