### ISSUE TITLE
Specification of interrupts, interrupt handlers, signals, signal handlers (Basic Embedded Abstract Machine: BEAM)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#169]
@japaric proposed the [Basic Embedded Abstract Machine](https://github.com/rust-lang/unsafe-code-guidelines/pull/111) (BEAM) as a way to specify what is legal in embedded programming when it comes to interrupts and interrupt handlers, and how they interact with Rust's aliasing. That document is a great start but needs some work before we want to merge it into the WIP directory. The PR got closed due to inactivity; this issue tracks BEAM so that it does not get lost.

@japaric also opened a bunch of PRs for specific questions on top of the BEAM. These should IMO all become their own separate issues, but there is no point in doing that before the BEAM PR is merged, so we just list them here:
* https://github.com/rust-lang/unsafe-code-guidelines/pull/112
* https://github.com/rust-lang/unsafe-code-guidelines/pull/113
* https://github.com/rust-lang/unsafe-code-guidelines/pull/114
* https://github.com/rust-lang/unsafe-code-guidelines/pull/115
* https://github.com/rust-lang/unsafe-code-guidelines/pull/116

**Comment by gnzlbg** [comment]
Regarding signal handlers, I recently run into this: https://github.com/rust-lang/rust/issues/30003

**Comment by JakobDegen** [comment]
Closing as based on a bunch now closed PRs
