### ISSUE TITLE
Abbreviation for zero-sized types with particular alignment

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/unsafe-code-guidelines#172]
We often need to talk about zero-sized types (ZSTs) with a particular alignment requirement, e.g., 1, or in general, N:

```rust
#[repr(align(N))] struct Zst;
```

It was suggested in https://github.com/rust-lang/unsafe-code-guidelines/pull/164#discussion_r303198338 that we should have an abbreviation for this defined in the glossary, where we also define the zero-sized type (ZST) abbreviation, to avoid writing "a zero-sized one-aligned type" and similar constructs all over the place.

A proposal was to use the `N-ZST` schema for an "N-aligned zero-sized type", e.g., `1-ZST` would stand for a "one-aligned zero-sized type".

**Comment by JohnScience** [comment]
`N-ZST` is a great name for talking about the concept in natural language, yet it has a great deficiency. Its particular instances, such as `4-ZST` or `16-ZST`, cannot be identifiers. [`aligned`](https://crates.io/crates/aligned) crate used `A1`, `A2`...`A64` as names for `1-ZST` ..= `64-ZST`. I'm unsure whether I should change the name of `A1` to, let's say, `A1ZST`. The latter may seem cryptic to the outsider.

**Comment by RalfJung** [comment]
Alternatively you could use `ZST4` etc, which avoids the cryptic `A`?

**Comment by JohnScience** [comment]
> Alternatively you could use `ZST4` etc, which avoids the cryptic `A`?

Perhaps, that's the best approach. The original author of `aligned` crate didn't make promises about `A1` being ZST, so there even might be no confusion.
