### ISSUE TITLE
Use "pictures" to explain degrees of freedom in struct and union layout

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#185]
In https://github.com/rust-lang/unsafe-code-guidelines/pull/160#discussion_r307714990 I suggested to use "pictures" to explain what happens when a `struct`/`union` is laid out (at least in terms of size and field offsets) and how we call the movable pieces there.

For structs:
```
[  <--> [field 1] <--> [field 2] <--> [field 3] <--> ]
```
This shows we can have leading, inner, and trailing "padding".

For unions:
```rust
[ <--> [field 1] <----> ]
[ <----> [field 2] <--> ]
[ <--> [ field 3 ] <--> ]
```
This shows that *for each field/variant*, we can have (separate) leading and trailing padding.

I think it would be nice to incorporate this into the document. But for this we basically need consensus that how big the padding is and (only for structs) in which order the fields come is the only freedom the compiler has to lay out these types. I am pretty sure that's true, e.g. we cannot split a field because you can take a reference to a field and that has to be using the layout of the type of that field -- but better safe than sorry. ;)

**Comment by Lokathor** [comment]
We can call it ASCII Art and be proud of it <3

**Comment by RalfJung** [comment]
I submitted a PR doing this for structs: https://github.com/rust-lang/unsafe-code-guidelines/pull/186

For unions I think this should happen in https://github.com/rust-lang/unsafe-code-guidelines/pull/161. It already contains all the rationale.

**Comment by RalfJung** [comment]
This has landed both for structs and unions.
