### ISSUE TITLE
Glossary formatting

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#191]
@Lokathor suggested to sort the glossary alphabetically, and I agree that makes sense. We have some PRs in flight that we should land first though, to avoid conflicts.

I am proposing we also change the headers from level 4 to level 3 (`#### Term` to `### Term`). Level 4 has the same font size as normal text, so it looks the same as normal bold text, which can be confusing.

Open Glossary PRs:
* [ ] https://github.com/rust-lang/unsafe-code-guidelines/pull/153
* [x] https://github.com/rust-lang/unsafe-code-guidelines/pull/190
* [x] https://github.com/rust-lang/unsafe-code-guidelines/pull/192
* [x] https://github.com/rust-lang/unsafe-code-guidelines/pull/161

**Comment by ehsanmok** [comment]
I will do that once they are merged.

**Comment by RalfJung** [comment]
@Lokathor also announced they would do it; please coordinate. :)

**Comment by Lokathor** [comment]
Oh I've got enough trouble wrangling `libm` to behave :3 feel free to let anyone else do the glossary thing.

**Comment by RalfJung** [comment]
All right, @ehsanmok it's yours.

**Comment by ehsanmok** [comment]
@RalfJung any update on this?

**Comment by RalfJung** [comment]
Oh, this got lost it seems...

https://github.com/rust-lang/unsafe-code-guidelines/pull/153 is still open but overall there was not much PR activity recently, so sorting and formatting it now would be fine I think.

**Comment by RalfJung** [comment]
(I might make a PR to just do these edits)
