### ISSUE TITLE
What are the validity invariants for `AtomicBool`?

### ISSUE THREAD

**Issue by asajeffrey** [rust-lang/unsafe-code-guidelines#208]
The validity invariant for `bool` is that it must be `0x01` or `0x00`. Does `AtomicBool` have the same requirement, or is it allowed to contain any `u8`? Under the hood, it's an `AtomicU8`, so the current implementation doesn't have the requirement of being a valid `bool`, but is this part of its contract?

**Comment by asajeffrey** [comment]
cc @nox and @RalfJung 

zuip chat: https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/Safe.20access.20to.20volatile.20memory

**Comment by nox** [comment]
Are there any public logs for the Zulip group?

**Comment by Lokathor** [comment]
You can log in to zulip with a GitHub account.

**Comment by bjorn3** [comment]
It does expose you email address to others though.

**Comment by elichai** [comment]
Well if you put anything that's not 0/1 there then this will be UB: https://doc.rust-lang.org/src/core/sync/atomic.rs.html#351

**Comment by asajeffrey** [comment]
@elichai Yes, the application I'm looking at doesn't provide mutable access, just `&AtomicBool`. AFAIK this is safe in the current implementation, but this isn't documented as being safe in future versions.

**Comment by RalfJung** [comment]
Right now, `AtomicBool` is defined as `UnsafeCell<u8>` and thus the validity invariant is the same as `u8`. But that might be considered an implementation detail.

But what is the motivation here? Why not just use `AtomicU8` if you intend to violate that invariant?

**Comment by Lokathor** [comment]
Possibly the same answer as with a lot of code: I" didn't write that part over there, I'm just trying to interface with it."

Or possibly, "I might expose this to C and I need to know if C will be able to make my data explode"

**Comment by asajeffrey** [comment]
I have a trait that says it's okay to take a `&T` even though the reference is to shared memory. The question is whether I can implement this trait for `AtomicBool` (assuming for the moment that I can for `AtomicU8`).

**Comment by nox** [comment]
I just woke up so maybe I'm missing some critical information, but if you can take an `&AtomicU8`, then you can also take an `&u8`, and you can probably do so both at the same time, which means it's also UB for `AtomicU8` or any other type with interior mutability.

**Comment by RalfJung** [comment]
I agree with @gnzlbg. Closing the issue then, unless someone thinks this should be added to a FAQ like I [suggested here](https://github.com/rust-lang/unsafe-code-guidelines/issues/205#issuecomment-540551014).
