### ISSUE TITLE
Dereferencing raw pointer to invalid data?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#216]
When I dereference a raw pointer but do not actually load any data, such as in `&raw const *x`, is there any validity requirement on the data it points to?

According to [the reference](https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html), the answer is "no". And indeed if the answer is "yes", it becomes impossible I think to do field-by-field initialization of a struct even with raw pointers. So "no" likely is the only possible answer.

This would mean that given a well-aligned, non-dangling `x: *const !`, doing `&raw const *x` is okay. Also, given a well-aligned, non-dangling  `x: *const (i32, !)`, doing `&raw const (*x).0` is okay. In the second case, whether the resulting ptr is actually usable relates to the layout of structs with uninhabited fields -- I recall a discussion with (I think) @rkruppe about this? There were some proposals on the table to make such structs zero-sized, but they [caused problems](https://github.com/rust-lang/rust/issues/49298) and IIRC the conclusion was that that's probably not possible.

To be sure about all of this, we should find a way to get that officially blessed by the lang team. Is there some reasonable place in the rustc repo or so where we could document this, and then FCP? Or do we need an RFC?

**Comment by Centril** [comment]
> In the second case, whether the resulting ptr is actually usable relates to the layout of structs with uninhabited fields -- I recall a discussion with (I think) @rkruppe about this? There were some proposals on the table to make such structs zero-sized, but they [caused problems](https://github.com/rust-lang/rust/issues/49298) and IIRC the conclusion was that that's probably not possible.

But to be explicit here, if we declare that `&raw const (*x).0` is OK, that does not have immediate impact on the zero-sizedness / uninhabitedness (from the POV of operational semantics, not type / match checking) of `*const (i32, !)`, right?

> Or do we need an RFC?

I would want a brief RFC mostly for its documentation and education value.

**Comment by RalfJung** [comment]
> But to be explicit here, if we declare that &raw const (*x).0 is OK, that does not have immediate impact on the zero-sizedness / uninhabitedness (from the POV of operational semantics, not type / match checking) of *const (i32, !), right?

Not immediately, no. Though it makes it strikingly clear that for unsafe code, making them zero-sized is a big hazard: given a well-aligned non-dangling `*const (i32, T)`, we couldn't even reliably get a raw pointer to the first field and write to it to initialize it. There might be no such field if `T` is uninhabited. That was @rkruppe's (I think) point the last time we discussed making uninhabited structs zero-sized.

**Comment by rkruppe** [comment]
See also discussion in #79 

My conclusion from past discussions is that making aggregates ZSTs if any components is uninhabited is in conflict with permitting piecewise initialization of aggregates, no matter whether it occurs in:

- safe Rust code (currently not allowed, but has been in the past and would be silly to disallow forever)
- unsafe Rust code (using raw pointers, as @RalfJung described)
- in MIR (after optimizations that remove temporaries in favor of direct moves to the eventual destination)

There have been a couple proposals to rescue at least the third use case (and possibly the first) but they significantly complicate the semantics of MIR both for miri and for lowering to LLVM IR, and they can't do anything for unsafe use case.

**Comment by RalfJung** [comment]
> safe Rust code (currently not allowed, but has been in the past and would be silly to disallow forever)

Actually even in safe Rust we can do things like
```rust
let x: (i32, !) = (13, return);
```

**Comment by RalfJung** [comment]
IMO the best way forward for the struct case is to revive @Centril's RFC that fixes partial initialization in safe code, so that this works:
```rust
let x: (i32, i32);
x.0 = 2;
x.1 = 4;
foo(&x);
```
Given that making ZST-uninhabited-structs work makes unsafe code handling partial initialization messy, makes MIR semantics and optimizations messy, [makes the data layout spec messy](https://github.com/rust-lang/unsafe-code-guidelines/pull/217) -- I think we should fully commit to not doing that and then ripe the benefits of that, which is exactly what this RFC does. Or am I hallucinating that @Centril wrote such an RFC once?

**Comment by Ixrec** [comment]
You are not hallucinating, although it's still got a few TODOs in it: https://github.com/Centril/rfcs/pull/16

**Comment by RalfJung** [comment]
@Centril sure. It doesn't specifically have to be that RFC, just any one that commits us to partial initialization. Either way we can then have a subsection in that RFC that says that by accepting the RFC we also commit to structs *always* being laid out as "all of their fields in some order with maybe some gaps between them".

**Comment by HeroicKatora** [comment]
Stable Rust already permits something that is effectively dereferencing a raw pointer without reading nor creating a reference to the place behind it (in unsafe code of course).

```
let _ = *ptr_to_invalid_data;
```

**Comment by moxian** [comment]
(I've randomly stumbled across this issue, and am not well versed in rust internals to be confident that what I'm saying makes sense. Please ignore me if this comment is more distracting than useful)

> This would mean that given a well-aligned, non-dangling `x: *const !`, doing `&raw const *x` is okay.
> Though it makes it strikingly clear that for unsafe code, making them zero-sized is a big hazard: given a well-aligned non-dangling `*const (i32, T)`, we couldn't even reliably get a raw pointer to the first field and write to it to initialize it. 

It appears to me, that this can be trivially sidestepped by saying that `(i32, !)` (or any composite type over `!`) is *never well-aligned* (by giving `!` impossible layout constraints.. somehow, I'm not sure of the details).
This effectively makes `*const(i32, !)` and `*const !` uninhabited, though, and that ship has already sailed... I'd be curious to know why `*const !` was not declared uninhabited from the start (I couldn't find any info on that), but that's severely offtopic, I admit.

> And indeed if the answer is "yes", it becomes impossible I think to do field-by-field initialization of a struct even with raw pointers

The following is currently not a valid syntax, but I don't see any obvious issues with making it valid (with an extra RFC, of course). Am I missing something?
```rust
struct S { a: i32, b: u64 };
fn init(s: *mut S){
  unsafe{ 
    *s.a = 5;
    *s.b = 8;
  }
}
```
(This would also - accidentally - improve ergonomics a bit by eliminating braces)

**Comment by Aaron1011** [comment]
> I'd be curious to know why *const ! was not declared uninhabited from the start (I couldn't find any info on that), but that's severely offtopic, I admit.

Raw pointers don't impose any constraints whatsoever on their contents  (ignoring uninitialized data for the moment). Their validity invariant is 'anything goes', if I understand the terminology correctly.

In particular, you can freely cast a raw pointer to and from a `usize`, without needing to care about whether or not the pointee is inhabited.

**Comment by moxian** [comment]
No, right, I understand that this is how it currently works.
My question is *why* is it like that (other than legacy reasons/historical accident)? I can't come up with a situation where casting `usize` (or any pointer) to `*const !` would be useful, yet *disallowing* such casts would resolve the problem of "Is it always safe to write to first element of `*mut (u32, T)`?" (with the answer of "yes, it is always safe because `*mut (u32, !)` does not exist at runtime")

**Comment by RalfJung** [comment]
> disallowing such casts would resolve the problem of "Is it always safe to write to first element of *mut (u32, T)?" (with the answer of "yes, it is always safe because *mut (u32, !) does not exist at runtime"

This could also be resolved by making `(i32,!)` have size 4, which it does currently. There's been discussion about this somewhere but I forgot where...

**Comment by KrishnaSannasi** [comment]
@RalfJung Are you thinking about [rust#49298](https://github.com/rust-lang/rust/issues/49298)

**Comment by RalfJung** [comment]
Well that was the start of it, but we had a chat with @rkruppe somewhere about this... but that one has all the links, yeah.

**Comment by KrishnaSannasi** [comment]
Ok, based on that I think it is from #37, (fixed the comment link). There is also this PR rust-lang/rust/pull/50622. Finally, there is #165 which is supposed to specify uninhabited types.

**Comment by RalfJung** [comment]
> When I dereference a raw pointer but do not actually load any data, such as in &raw const *x, is there any validity requirement on the data it points to?

Meanwhile we have [decided](https://github.com/rust-lang/reference/pull/1387) that the `*` projection itself is never UB, so in particular the validity of the data behind the pointer indirection is definitely irrelevant.
