### ISSUE TITLE
Fn* trait and fn pointers

### ISSUE THREAD

**Issue by elichai** [rust-lang/unsafe-code-guidelines#218]
Hi, bare function pointers have been defined https://github.com/rust-lang/unsafe-code-guidelines/issues/14

What isn't written properly is the relationship of fn pointers and the Fn/FnMut/FnOnce traits.

Can you cast them to function pointers? Are they something completely different?
(obviously if anyone on stable could ever implement them on his own types they'll be unrelated to fn pointers. But it's unstable for now at least) 

EDIT: Apparently there's a segmentation fault if you try to do transmute `FnOnce()` generic reference to `fn()` and miri complains about `type validation failed: encountered a pointer, but expected a function pointer` https://play.rust-lang.org/?gist=41bc07d360a8d17ea21a5aacc7178384

**Comment by gnzlbg** [comment]
> What isn't written properly is the relationship of fn pointers and the Fn/FnMut/FnOnce traits.

The `Fn` traits are _just traits_ that some types implement - these implementations are documented here: https://doc.rust-lang.org/std/ops/trait.Fn.html

> Apparently there's a segmentation fault if 

As @rkruppe pointed out in zulip, this works: https://play.rust-lang.org/?gist=41bc07d360a8d17ea21a5aacc7178384 

Your example transmutes a pointer to a function pointer (`&print` is a `&fn() -> i32`) into a function pointer `fn() -> i32`, and that's incorrect.

---

Also, this might be an XY problem: why do you need to obtain a `fn` type from a `Fn` trait ?

**Comment by elichai** [comment]
I want to know if it's possible to use these traits to pass function pointers to C

**Comment by gnzlbg** [comment]
> I want to know if it's possible to use these traits to pass function pointers to FFI(C)

If you have a `T: Fn`, the only thing you know is that `T` implements the trait `Fn`. `T` might be a function pointer, but it my also be a ZST or a closure. 

Can you show an example of your particular application that shows how you plan to pass that `T` to FFI without knowing its actual concrete type ?

**Comment by elichai** [comment]
Option 1 is something like that: https://play.rust-lang.org/?gist=d6eb0aaae309c12c2cb66b1d123f06e7

Option 2 is to pass a real function as function pointer and the FnMut trait as raw data. https://play.rust-lang.org/?gist=d3ea75e85ce4f1571330a1a054b99324

**Comment by gnzlbg** [comment]
@elichai you can do [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=a05b94bb04a425d4c241f4e1ebd4d33a) but none of this has much to do with the unsafe code guidelines.

**Comment by elichai** [comment]
Sorry. Yeah. The point that I think is related to the guidelines is that the traits Fn* aren't directly related to "functions" they're type who might contain a function but they aren't functions. (so you cannot pass them to FFI as function pointers)

**Comment by elichai** [comment]
> @elichai you can do [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=a05b94bb04a425d4c241f4e1ebd4d33a) but none of this has much to do with the unsafe code guidelines.
> 
> (EDIT: @Mark-Simulacrum showed that [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1724f23737ba421fd103e63db8a70373) also does it)

Is working==correct here?

**Comment by bjorn3** [comment]
> Is working==correct here?

No, it relies on the implementation of the `rust-call` abi. (keep self arg, and unpack the second tuple arg as if the elements were separate arguments, eg `extern "rust-call" fn(&self, (u8, u16))` -> `fn(&self, u8, u16)`.)

**Comment by elichai** [comment]
Exactly what I thought :)
I think this can only be safe with an `extern "C"`  (as I showed here: https://play.rust-lang.org/?gist=d3ea75e85ce4f1571330a1a054b99324)

**Comment by gnzlbg** [comment]
> Is working==correct here?

Yes, check @Mark-Simulacrum version, it is correct independently of the Rust call ABI because the Rust compiler knows the ABI in both the `extern "C"` definition and within the closure.

**Comment by elichai** [comment]
If i understand you correctly, for this code to actually be C compatible the declaration should look more like this:
`extern "C" fn c_fn(cb: extern "C" fn(data: *const c_void), d: *const c_void);`

which will obviously won't let you pass in a closure.

**Comment by gnzlbg** [comment]
> If i understand you correctly, for this code to actually be C compatible the declaration should look more like this:

No, it works fine with `cb: extern "Rust" fn(data: *const c_void)`. Rust code can call other Rust code - that's _why_ this works fine.

**Comment by elichai** [comment]
@gnzlbg I said "C compatible". so in reality it will be like
```
extern "C" { fn c_fn(cb: extern "C" fn(data: *const c_void), d: *const c_void); }
```
and then linked against a C compiled lib.

**Comment by gnzlbg** [comment]
@elichai So yeah, it depends. You can compile a Rust crate exporting the `pub extern "C" fn c_fn(cb: fn(data: *const c_void, d: *const c_void) { ... }` as a `cdylib`, and link that library with other other Rust code just as if it were a normal C library, and if that Rust code declares it as `extern "C" { fn c_fn(cb: fn(data: *const c_void, d: *const c_void); }`, then that's guaranteed to work. 

The tricky part is if you want to implement the `extern "C" fn c_n(...)` function yourself, in a language that's not Rust. Then if you use `extern "Rust"` for the callback need to rely on unspecified details of the Rust call ABI that can change any time. In that case, you can just use the `"C"` ABI in your implementation, e.g, [like so](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1724f23737ba421fd103e63db8a70373).

**Comment by RalfJung** [comment]
I don't see a concrete question left here to be answered, so I am going to close this. If there are still open questions, please respond with a more concrete example of what is unclear.
