### ISSUE TITLE
pointer arithmetics 

### ISSUE THREAD

**Issue by elichai** [rust-lang/unsafe-code-guidelines#221]
Right now there's unsafe pointer offset/add/sub and the "safe" wrapping offset/add/sub.
now all of these call llvm instructions.

But then you read the docs and see `If you need to cross object boundaries, cast the pointer to an integer and do the arithmetic there.`

so why doesn't all pointer arithmetic is done via casting?
it seems like the actual assembly is equivalent right now: https://godbolt.org/z/ytfCDD

**Comment by bjorn3** [comment]
> so why doesn't all pointer arithmetic is done via casting?

To give the optimizer more guarantees.

> it seems like the actual assembly is equivalent right now

That is because it is a simple example where optimizations can't do much anyway.

**Comment by elichai** [comment]
@bjorn3 you're right. it looks like the optimizer is blind to the ptr->usize->ptr casting and can't optimize it out like the rest https://godbolt.org/z/ZMJhUD

**Comment by RalfJung** [comment]
LLVM also performs some incorrect optimizations around ptr->int->ptr casts: https://bugs.llvm.org/show_bug.cgi?id=34548

**Comment by RalfJung** [comment]
I think the question here has been answered.
