### ISSUE TITLE
Pointers to DSTs with the same layout as a slice?

### ISSUE THREAD

**Issue by shlevy** [rust-lang/unsafe-code-guidelines#226]
I'm working on a non-empty slice crate:

```rust
#[repr(C)]
pub struct NonemptySlice<T> {
    first: T,
    rest: [T],
}
```

From my read of the existing guidelines and my previous experience with the C standard, I would expect this to have the same layout as `[T]` with the appropriate length. However, despite `&[T]` having a well-defined layout `&NonemptySlice<T>` does not.

1. Are all of the interpretations above correct?
2. In practice, is a cast between `&[T]` and `&NonemptySlice<T>` going to be a problem if I know the slice has at least one element?
3. Should this special case of a DST pointer be specified?

**Comment by shlevy** [comment]
Actually I'm guessing now this *won't* work, because if a `&NonemptySlice<T>` is in fact a struct with a pointer and a length, the length is probably the size of `rest`, not the full slice. And I'm guessing we're not ready to guarantee that even if that's right in the current impl?

**Comment by Ixrec** [comment]
Yeah, I would semi-expect `[T]` <-> `NonemptySlice<T>` transmutes to work, but there's no way to make `&[T]` <-> `&NonemptySlice<T>` transmuting work without some sort of "first-class custom DSTs"/"custom fat pointers" feature that doesn't exist in the language today.

**Comment by Lokathor** [comment]
I suspect you could write a valid deref impl, but not a direct transmute

**Comment by RalfJung** [comment]
> And I'm guessing we're not ready to guarantee that even if that's right in the current impl?

You are guessing correctly. The only support ways to interacts with slices is calling `as_ptr` and `len` to get their components, and calling `from_raw_parts` to construct them.

**Comment by Lokathor** [comment]
```rust
impl<T> Deref for NonemptySlice<T> {
  type Output = [T];
  fn deref(&self) -> &[T] {
    unsafe {
      let l = self.rest.len() +1;
      assert!(l < isize::max_value() as usize);
      core::slice::from_raw_parts(self as *const T, l)
    }
  }
}
```

**Comment by shlevy** [comment]
OK, closing this for now then. Guess this waits for custom DSTs.
