### ISSUE TITLE
Please update the format used for build config imports on Travis CI

### ISSUE THREAD

**Issue by svenfuchs** [rust-lang/unsafe-code-guidelines#228]
I am opening this issue here to raise the right people's attention. Please see https://github.com/rust-lang/simpleinfra/issues/33 for details.

**Comment by RalfJung** [comment]
@svenfuchs  So just to be sure, the fix is to replace `rust-lang/simpleinfra/travis-configs/static-websites.yml` by `rust-lang/simpleinfra:travis-configs/static-websites.yml`, and that's it?

**Comment by pietroalbini** [comment]
Fixed.
