### ISSUE TITLE
What are the exact semantics of pointer comparison?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#239]
Pointer comparison is [complicated](https://internals.rust-lang.org/t/comparing-dangling-pointers/3019). However, for better or worse, Rust lets you safely compare any raw pointers, so we need to assign this some reasonable semantics. I wanted a place to centrally track all questions related to this, so here we go. (I never know whether to open such issues here in the UCG repo, or over in the rustc repo.)

There are two ways in which pointer comparison is "interesting": provenance, and objects without a guaranteed stable address.

## Provenance

Does provenance affect whether pointers are equal? One major concern here is figuring out the semantics of pointer comparison in LLVM, and then likely we have no choice but to inherit that. Some data points:
* Eli Friedman [writes](https://bugs.llvm.org/show_bug.cgi?id=34548#c99)
    > icmp is defined to just take the raw pointer bits as an integer.  This is described in LangRef.  If the text of LangRef describing icmp isn't sufficiently clear, suggestions welcome.  If some transform isn't consistent with this, please file a bug.
* In our [LLVM semantics paper](https://people.mpi-sws.org/~jung/twinsem/twinsem.pdf), we made pointer comparison non-deterministic under some conditions (when the addresses are equal but provenance differs), so that pointers derived from different calls to `malloc` can always compare inequal even if they are physically equal. This directly contradicts Eli's statement above.

I am trying to figure out if LLVM optimizations clearly indicate one or the other choice; so far that has been inconclusive.

## Unstable objects

Functions, vtables, and consts do not have a unique stable address, also leading to interesting problems.

### function address equality

* https://github.com/rust-lang/rust/issues/54685: Inconsistent behavior when comparing function pointers in release
* https://github.com/rust-lang/rust/issues/70861: function pointers as match patterns have optimization-dependent behavior
* https://github.com/rust-lang/rust/issues/73722: Invalid equality check result for usizes obtained from function pointers

### vtable equality

* https://github.com/rust-lang/rust/issues/46139: vtable addresses differ based on the number of codegen units
* https://github.com/rust-lang/rust/issues/69757: Consider warning when comparing wide pointers with vtables (as their address identity is unstable)

### const address equality

* [Some interesting observations](https://internals.rust-lang.org/t/constifying-the-std-core-library/12962/4?u=ralfjung)

**Comment by RalfJung** [comment]
This is a somewhat interesting example:
```rust
extern crate libc;
use std::mem;
pub fn test(ext: bool) -> bool { unsafe {
    let x = libc::malloc(mem::size_of::<i32>()) as *mut i32;
    *x = 0;
    if ext { libc::free(x as *mut _); }
    let y = libc::malloc(mem::size_of::<i32>()) as *mut i32;
    *y = 0;
    return x == y;
} }
```
It gets optimized to `return false`, so this looks a bit like ptr comparison does not look at the actual address, since ptr reuse could have happened. But then, ptr reuse also could have *not* happened, and LLVM assumes that the allocator itself is not observable. (I don't know if it assumes that just for `malloc` or also for e.g. custom Rust allocators. In case of the latter, that would be an interesting and so far undocumented piece of possible UB.) So arguably, even under the strict "compare int addresses", this optimization is correct.

**Comment by RalfJung** [comment]
Also see [this LLVM bug](https://bugs.llvm.org/show_bug.cgi?id=46380).

**Comment by tmiasko** [comment]
The optimization from https://github.com/rust-lang/unsafe-code-guidelines/issues/239#issuecomment-645216912 is based on the assumption that LLVM is allowed to substitute its own allocation function and guarantee particular outcome of the comparison.

Those kind of optimizations are also applicable to Rust allocation functions, since rustc explicitly opt ins for this behaviour for `rust_alloc`, `rust_dealloc` and `rust_realloc`.

**Comment by RalfJung** [comment]
Right. But it is unclear to me howto actually make that formally precise. Like, how could we implement support for custom allocators in Miri in a way that it detects UB when the allocator works in a way that breaks the above optimization?

**Comment by RalfJung** [comment]
I updated the OP to also link to various issues about function pointer and vtable equality.

**Comment by RalfJung** [comment]
I entirely forgot that `const` are another example of objects without stable addresses; [that can lead to some interesting effects as well](https://internals.rust-lang.org/t/constifying-the-std-core-library/12962/4?u=ralfjung).

**Comment by RalfJung** [comment]
I think the interactions with provenance are largely clear at this point -- provenance does not affect comparison (except maybe as part of the resolution to https://github.com/rust-lang/unsafe-code-guidelines/issues/328).
I opened https://github.com/rust-lang/unsafe-code-guidelines/issues/522 to track the question of what we guarantee about the pointer identity of compile-time-created objects.
