### ISSUE TITLE
Interior mutable shared ref to constant memory is UB even when not writing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#246]
Current Stacked Borrows makes this UB:
```rust
fn main() { unsafe {
    let x = &0usize;
    let y: &std::cell::Cell<usize> = std::mem::transmute(x);
} }
```
To be honest I do not think there is a good reason for this. We cannot optimize much around interior mutable types, so I don't think we should require them to be writable unless we are actually mutating.

**Comment by programmerjake** [comment]
Closely related, but perhaps distinct:

```rust
fn main() {
    unsafe {
        let x = &0usize;
        let y: &std::sync::atomic::AtomicUsize = std::mem::transmute(x);
    }
}
```

**Comment by RalfJung** [comment]
This is closely related to https://github.com/rust-lang/unsafe-code-guidelines/issues/227: basically, interior mutable shared references should inherit the parent pointer permission instead of asserting mutability, and again we have a close relationship between what we do for raw pointers and what we do for interior mutable shared references.

@programmerjake that's the exact same case. `AtomicUsize` and `Cell<usize>` look the same to the compiler (both are `UnsafeCell<usize>`).

**Comment by RalfJung** [comment]
Closing as a duplicate of https://github.com/rust-lang/unsafe-code-guidelines/issues/303.
