### ISSUE TITLE
Stacked borrows page refers to Alias(None)

### ISSUE THREAD

**Issue by Storyyeller** [rust-lang/unsafe-code-guidelines#296]
The stacked borrows page says " the initial pointer to that memory has tag Alias(None).", but it does not explain what `Alias(None)` is supposed to mean. I suspect this is supposed to refer to `Tag::Untagged` instead.

**Comment by RalfJung** [comment]
Good catch, thanks! Fixed in https://github.com/rust-lang/unsafe-code-guidelines/pull/297. The docs were also out-of-date so I updated them.
