### ISSUE TITLE
ManuallyDrop layout guarantees?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/unsafe-code-guidelines#302]
The docs for [`ManuallyDrop`](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop.html) state:

> `ManuallyDrop<T>` is subject to the same layout optimizations as `T`.

This hints, but does not explicitly guarantee, that `ManuallyDrop<T>` has the same layout as `T`. Do we want to guarantee that?

**Comment by joshtriplett** [comment]
This seems right to me as well; `repr(transparent)` needs to guarantee this, and the fact that `ManuallyDrop` is `repr(transparent)` seems like a very public and required part of `ManuallyDrop`'s ABI that we cannot and should not change.

**Comment by joshlf** [comment]
Is there a path forward to this becoming an official position of the UCG WG? Not sure what the rules of parliamentary procedure are for the WG 😛

**Comment by Lokathor** [comment]
Nothing anywhere in this repo is official.

The intended path is that when something is ready to be official then it should just go though the RFC process.

**Comment by RalfJung** [comment]
We really need some procedure by which to declare a libstd `repr(transparent)` as an explicit stable guarantee...

**Comment by ChayimFriedman2** [comment]
I guess this should be closed? rust-lang/rust#88375 is merged by now.
