### ISSUE TITLE
Should Rust permit conversions between pointers to data and pointers to functions?

### ISSUE THREAD

**Issue by eternaleye** [rust-lang/unsafe-code-guidelines#309]
From https://github.com/rust-lang/rfcs/pull/1861#issuecomment-280486711

> @briansmith
>
> > Maybe we're talking past each other, but I would expect an extern type `T` to be guaranteed to not be a function pointer, just like `struct T;` is guaranteed to not point to a function in C.
>
> Ah, I was not aware of that! (But also slight terminology tweak: It'd be `*const T`, not `T`, that would be a function pointer.) For anyone else who may have been in the same position as I was, the C99 standard says:
>
> > 6.3.2.3:8 A pointer to a function of one type may be converted to a pointer to a function of another type and back again; the result shall compare equal to the original pointer. If a converted pointer is used to call a function whose type is not compatible with the pointed-to type, the behavior is undefined.
>
>(As this gives no conversions between data pointer types and function pointer types, such conversions are undefined, and thus a pointer to one can't possibly be valid as a pointer to the other.)
>
> The rationale I saw given when I looked was that data and function pointers may not be the same size.
>
> However, Rust is not C, and this should probably fall under the aegis of the Rust unsafe semantics - permitting it may be of value. I've [filed an issue](https://github.com/nikomatsakis/rust-memory-model/issues/36) raising that question.

Note that this requires _having_ function pointer types, which we currently do not , and was something I thought RFC 1861 might make possible - the closest is a kind of "function reference of static lifetime" that is syntactically not a reference at all :(

**Comment by JakobDegen** [comment]
Closing in favor of #72 , #340 , and some T-lang issues
