### ISSUE TITLE
Layout of single-field structs

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/unsafe-code-guidelines#34]
PR #31 identified this as an area for continued discussion. Specifically, if you have a struct with single field (`struct Foo { x: T }`), should we guarantee that the memory layout of `Foo` is identical to the memory layout of `T` (note that ABI details around function calls may still draw a distinction, which is why `#[repr(transparent)]` is needed). What about zero-sized types like `PhantomData`?

@rkruppe [wrote](https://github.com/rust-rfcs/unsafe-code-guidelines/pull/31#issuecomment-426730654):

> Long ago I proposed that we might want to guarantee (some subset of) newtype unpacking for repr(Rust) structs. @nikomatsakis carried this over into #11 as discussion point but it received no further discussion. I like to think that means it's uncontroversial 😄 I've also never heard of any reason why one might not want that to be true.
> 
> To make a specific proposal, let's restrict it to structs [1] that contain a single field having the same _memory layout_ as the type of the sole field. So `struct Foo<T>(T);` and `struct Foo<T> { x: T }` would be laid out like `T` in memory, though possibly still passed differently in function calls.
> 
> [1] The same guarantee for `(T,)` are already covered by the special case of homogeneous tuples being laid out like arrays that is already in this PR.

**Comment by nikomatsakis** [comment]
I believe we should make this guarantee. I would further like to say that it applies to any struct with a single field of non-zero size. 

cc @eddyb @gankro

**Comment by the8472** [comment]
This would automatically fall out of #36, correct?

**Comment by Gankro** [comment]
I am a big +1 on making newtyping a layout (but not ABI) no-op

**Comment by RalfJung** [comment]
If we adopt what @Gankro said, then this is indeed a subset of #36: After removing (size: 0, align: 1)-types, a "single-field struct" (according to the definition, having a single non-ZST field where I guess we mean ZST with alignment 1) is certainly homogeneous.

So if we say those are like an array, we'd get that single-field structs are like 1-element arrays. Should we guarantee that those are like their element type (except for ABI)? Seems sensible to me.

**Comment by rodrimati1992** [comment]
Would the compiler be allowed to change the layout of types containing a #[repr(transparent)] type relative to the type it is wrapping?

```

#[repr(transparent)]
struct Transparent<T>(T)

fn is_transparent<T>()->bool{
    is_the_same_memory_layout::<Transparent<T>,T>()&&
    is_the_same_memory_layout::<Vec<Transparent<T>>,Vec<T>>()&&
    is_the_same_memory_layout::<Box<Transparent<T>>,Box<T>>()&&
    is_the_same_memory_layout::<Arc<Transparent<T>>,Arc<T>>()&&
    is_the_same_memory_layout::<HashMap<Transparent<T>>,HashMap<T>>()
}



```
Would this (hypothetical) function return true for all `T` ?

**Comment by Gankro** [comment]
Is there any particular reason why you think `repr(transparent)` is significant here? (I would indeed expect your assertion to pass, even if `Transparent<T>` weren't marked as `repr(Transparent)`).

**Comment by rodrimati1992** [comment]
> Is there any particular reason why you think `repr(transparent)` is significant here? (I would indeed expect your assertion to pass, even if `Transparent<T>` weren't marked as `repr(Transparent)`).

That was just in case that it made a difference.

**Comment by nikomatsakis** [comment]
There's been some interesting examples of why the "single-field layout guarantee" would be useful in rust-lang/rust#53514.

**Comment by nikomatsakis** [comment]
@rodrimati1992 

> Would the compiler be allowed to change the layout of types containing a `#[repr(transparent)]` type relative to the type it is wrapping?

As @Gankro said, I think that this issue basically proposing the answer is "no" -- and further that `#[repr(transparent)]` is not necessary (that attribute only affects the function call ABI, not memory layout, afaik).

**Comment by nikomatsakis** [comment]
It seems to me there is a general consensus here that this is a good idea. I like the observation that this is a subset of #36, I had not realized that. But I agree with @rkruppe it's worth calling out on its own regardless.

**Comment by gnzlbg** [comment]
offtopic: do we have a definition of `repr` somewhere? the attribute controls memory layout, function call abi, etc. I found this a bit confusing.

**Comment by nikomatsakis** [comment]
@gnzlbg There is no central listing of all the knobs, but that seems like a good thing for the language reference. The structs section includes some discussion of struct-specific representation.

**Comment by kupiakos** [comment]
Could there be optimization cases where it'd be desirable to over-align a struct based on its usage? Say you have a `Foo([u8; 3])`  and a profile-based optimization pass recognizes that giving `Foo` an 8-byte alignment requirement would improve performance.
