### ISSUE TITLE
Miri errors link to wip/stacked-borrows.md, which is no longer accurate

### ISSUE THREAD

**Issue by saethlin** [rust-lang/unsafe-code-guidelines#358]
Things I noticed on a quick skim just now

- [ ] Mentions of `Untagged` ~~and no explanation of `Wildcard`~~
- [ ] Copy+paste of the old code inside Miri (should probably become pseudocode or paste the new code)
- [ ] "We do not recurse into fields of structs or other compound types" but we have `-Zmiri-retag-fields`

**Comment by RalfJung** [comment]
I don't think that page should explain `Wildcard`. `Wildcard` is not part of the Stacked Borrows specification. It is part of Miri's approximation for the semantics of `from_exposed_addr`.

**Comment by RalfJung** [comment]
>  Copy+paste of the old code inside Miri (should probably become pseudocode or paste the new code)

The code still describes behavior correctly, and is simpler than the new code, so I don't see this as a bug, and I see it as a feature.
