### ISSUE TITLE
Is a ZST C-variadic parameter equivalent to a non-present parameter?

### ISSUE THREAD

**Issue by kupiakos** [rust-lang/unsafe-code-guidelines#378]
Is the following:

```rust
unsafe { printf(b"hello %d %d world\n\0".as_ptr().cast(), 10i32, (), 20i32, ()) };
```

Equivalent to:

```rust
unsafe { printf(b"hello %d %d world\n\0".as_ptr().cast(), 10i32, 20i32) };
```

If the former is allowed, and passing a ZST as a variadic parameter is equivalent to the parameter being non-present, this makes a safe `printf` wrapper macro I'm writing much simpler while remaining extensible. I can confirm that this compiles and runs as expected on my platform (ZST has no effect), but since I can't find any docs referencing this, I don't want to rely on that behavior without some sort of stability promise 😄

**Comment by bjorn3** [comment]
No, there are some targets that don't ignore ZST arguments. See https://github.com/rust-lang/rust/blob/d121aa3b5584eb919a4aaf64dbae0ea1e8e30231/compiler/rustc_ty_utils/src/abi.rs#L356-L367

**Comment by kupiakos** [comment]
I had assumed that even though ZST arguments aren't always ignored generally, the variadic structure passed in couldn't observe the ZST. However, [this is not the case for `x86_64-pc-windows-gnu`](https://godbolt.org/z/fffsKeMfn).
