### ISSUE TITLE
Sound ways to work with self-referential futures

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/unsafe-code-guidelines#380]
Hi! I have relatively complex code that passed Miri previously but doesn’t pass it now.

The failing job is:
https://github.com/GoldsteinE/name-it/actions/runs/3594297524/jobs/6052384905

TL;DR: I’m doing something like this:

```rust
let x: Fut = async_function();
let y: [MaybeUninit<u8>; size_of::<Fut>()] = transmute(x);
let p = pin!(y); // Causes a retag!
let z: Pin<&mut Fut> = transmute(p);
z.poll();
```

As far as I understood, this is a general issue with soundness of futures (https://github.com/rust-lang/rust/issues/63818). I’d be grateful for any pointers to things I could do to resolve this issue in my case on my side.

**Comment by GoldsteinE** [comment]
It sadly doesn’t reproduce on more minimal example. I’ll try to minify the full version properly.

**Comment by RalfJung** [comment]
Which was the last version of Miri where this still worked?

**Comment by GoldsteinE** [comment]
That’s an interesting question, I’ll check it.

**Comment by GoldsteinE** [comment]
Ok, so, turns out this particular snippet:

1. Failed before my pipelines started failing
2. Fails without transmute shenanigans or any unsafe code at all: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a408d5a73049f532280398b2a8559b01

As this reproduces without unsafe code, this is a bug either in `futures`, `std` or Miri.

**Comment by RalfJung** [comment]
Okay, it's probably field-retagging-by-default then that broke this.

Looking at the code, my first impression is that this is unsound since `Arr` is `Unpin`.  Currently the alias handling of mutable references is tied to the `Unpin` trait. This is a temporary hack and not a stable guarantee (see [this discussion](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines) for work towards a proper solution), but in this case probably adding `Unpin` would both fix that soundness bug and make Miri stop complaining?

**Comment by GoldsteinE** [comment]
It seems like there’re two issues: one that affects `futures` and another that only affects transmute hack.

name-it code handles `Unpin` correctly, so that's not it

**Comment by GoldsteinE** [comment]
Or maybe that's a single issue  that name-it just masked for older Miri versions. Either way, those issues seem to be very related.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/unsafe-code-guidelines/issues/381, which describes the core problem more precisely. Thanks for the report, which lead to be discovering this underlying problem!

> Or maybe that's a single issue that name-it just masked for older Miri versions. Either way, those issues seem to be very related.

Yeah that is possible, but pretty hard to say until we figure out https://github.com/rust-lang/unsafe-code-guidelines/issues/381.
