### ISSUE TITLE
Soundness of atomic `get_mut()` for reading whether a value was initialized by another thread?

### ISSUE THREAD

**Issue by anp** [rust-lang/unsafe-code-guidelines#383]
Hi! I have a question that is a bit odd but I'm having a hard time convincing myself [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b3df03112d7c24f7cc9459b6ab62a42d) is sound:

```rust
fn main() {
    let shared = RwLock::new(AtomicBool::new(false));
    let mut to_init: MaybeUninit<u32> = MaybeUninit::uninit();

    scope(|s| {
        s.spawn(|| {
            to_init.write(10);
            shared.read().unwrap().store(true, Ordering::Release);
        });
    });

    // Are we guaranteed to see the atomic write here?
    // If so, what gives us that property? It's not atomic operations on this address.
    assert!(*shared.write().unwrap().get_mut());
    
    // What makes this sound?
    assert_eq!(unsafe { to_init.assume_init() }, 10);
}
```

AIUI, using atomic orderings when reading from an atomic variable is the way to guarantee that the reader sees all mutations applied by other threads (creating a happens-before relationship?). In this snippet, the thread which attempts to observe the mutation doesn't use any atomic ordering, and I'm not clear on how we guarantee that it will see the stored value.

Where I'm confused is I'm pretty sure this is sound when using a non-atomic boolean, and I don't know how atomic operations could cause *less* consistent results than totally unsynchronized ones, but I can't find anything in the reference or LLVM's memory ordering spec that guarantees the `get_mut()` call will see the other thread's mutation.

**Comment by RalfJung** [comment]
`scope` will perform synchronization with all threads spawned in that scope. That adds a happens-before edge between the end of that thread, and the return of `scope`. Therefore the non-atomic read in `get_mut` happens-after the atomic store in the thread. (And he same would be true if that was a non-atomic write.) Also for that reason, and even entirely independent of `shared`, the non-atomic read in `to_init.assume_init()` happens-after the non-atomic write in `to_init.write(10)`.

Don't look at the LLVM docs, LLVM uses a memory model that is different from C++ and Rust. The reference links [here](https://en.cppreference.com/w/cpp/atomic/memory_order) for more details on the C++ orderings, but that is not a great learning resource -- and honestly I don't know a great resource to learn this weak memory model stuff.

Note that having an `AtomicBool` inside an `RwLock` is redundant, you don't need to synchronize twice.

**Comment by anp** [comment]
That cppreference link is very helpful! IIUC in those terms:

1. joining the spawned thread or acquiring a lock means that the scoped thread *synchronizes-with* the main thread
2. main thread synchronizing-with scoped thread creates an *inter-thread happens-before* edge where the scoped thread's evaluations happens-before the main thread's
3. non-atomic accesses to values that were modified with atomic operations is only UB if there exists no happens-before edge between the write & read evaluations

I think the piece I was missing here is that `synchronizes-with` creates dependencies beyond the specific memory location which is synchronized. Thanks!

**Comment by afetisov** [comment]
@RalfJung This question is about `scope` exit, but we can make the same example with `thread::spawn` instead of `thread::scope`, and `Arc<RwLock<AtomicBool>>` instead of `&RwLock<AtomicBool>`. The locks are supposed to eliminate data races when accessing the contents - but how does this interact with atomic accesses? We can even decouple the lock and the atomic, so that the question becomes: is this code sound? ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7540f0c8564a4396bab948241732a2fd)) Miri doesn't complain.

```rust
#![feature(atomic_mut_ptr)]

use std::{
    sync::{atomic::{AtomicBool, Ordering}, Mutex},
    thread::{self, sleep},
    time::Duration
};

static FLAG: AtomicBool = AtomicBool::new(false);
static LOCK: Mutex<()> = Mutex::new(());

pub fn main() {
    thread::spawn(|| unsafe {
        let _lock = LOCK.lock().unwrap();
        // Non-atomic write to an atomic static
        *FLAG.as_mut_ptr() = true;
    });

    // Will we ever see the write?
    loop {
        let lock = LOCK.lock().unwrap();
        // Atomic load corresponding to non-atomic read, 
        // but both operations are guarded by a mutex. 
        if FLAG.load(Ordering::Acquire) {
            break;
        }
        drop(lock);
        sleep(Duration::from_millis(1));
    }
    println!("Done!");
}
```

**Comment by RalfJung** [comment]
You could even make the `FLAG.load` non-atomic, since all FLAG accesses are protected by the lock.
