### ISSUE TITLE
Document that it is okay to temporarily have invalid data behind an `&mut T`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#386]
As part of [this discussion](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/RFC.202195.20and.20enum.20validity), it seems we have general consensus that  "it is acceptable to write bytes through a pointer derived from &mut T even if those bytes make the T invalid so long as the T is made valid again before the lifetime that would be given to the pointer if it were a reference expires and the parent &mut T is usable again."

Specifically, this is fine:
```rust
fn main() {
    let mut b = false;
    let ptr = &mut b as *mut bool as *mut u8;
    unsafe {
        *ptr = 2;
        *ptr -= 1;
    }
    assert!(b);
}
```

We should probably document this as UCG consensus, and maybe even find a way to get t-lang to sign off on this, though it seems unclear how to best do that.

This is helpful because it means the code in https://github.com/rust-lang/rfcs/issues/2195 is fine without having to weaken the notion of validity of those enums specifically.

**Comment by Darksonn** [comment]
This seems like it's just a weaker version of #346.

**Comment by RalfJung** [comment]
I would call it a weaker version of https://github.com/rust-lang/unsafe-code-guidelines/issues/84. But yeah it overlaps with both of those discussions - without finally resolving either of them.
