### ISSUE TITLE
Validity invariant for containers with unitialized data

### ISSUE THREAD

**Issue by hackaugusto** [rust-lang/unsafe-code-guidelines#393]
I hope this is a good channel to ask this, let me know if I should use something else :)

I was trying to grasp what is considered UB w.r.t. uninitialized data. My current understanding is that there are [validity](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#validity-and-safety-invariant) rules, and that by definition uninitialized data is not valid for any type except `union` and `padding`.

From what I understood from the [reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) UB happens when the value is produced, and it describes it as:

> "Producing" a value happens any time a value is assigned to or read from a place

It seems there is an issue with that definition for code like this:

```rust
let mut v: Vec<i32> = Vec::with_capacity(1);
unsafe { v.set_len(1) }
```

IIUC that second line above should be UB, but the rule of producing doesn't seem to cover that, since there is no data being assigned or read.

My questions are: 1. is it correct to say the above is undefined behavior? 2. am I missing some other rules that would define the above as UB?

Thanks!

**Comment by RalfJung** [comment]
This code is not intended to be (language-level) UB. It violates safety requirements but not validity requirements. This means that calling other *safe* Vec operations later can cause UB (e.g. `v.pop()`).

**Comment by hackaugusto** [comment]
@RalfJung thanks for the reply!

Oh, okay, I was interpreting `v.set_len(1)` to be the same as `v.push(MaybeUninit::uninit().assume_init())` and that it wasn't defined as UB was just a quirky of the producing definition.

But what you're saying is that I can have memory with typed as `i32` with uninitialized bits as long as I don't look at it. So the code below does not have UB?

```rust
let mut v: Vec<i32> = Vec::with_capacity(1);
unsafe { v.set_len(1) }
v[0] = 1i32;
```

**Comment by deltragon** [comment]
> But what you're saying is that I can have memory for a type i32 with uninitialized bits as long as I don't look at it. So the code below does not have UB?
```rust
let mut v: Vec<i32> = Vec::with_capacity(1);
unsafe { v.set_len(1) }
v[0] = 1i32;
```
The third line here adds an additional question, as it creates an `&mut i32` (through the `IndexMut::index_mut()` desugaring), which points to uninitialized memory. This seems to be allowed if I understand https://github.com/rust-lang/unsafe-code-guidelines/issues/346 correctly, but is not officially documented yet. (Additionally, I'm not sure if the write to `&mut uninit` is allowed).

**Comment by hackaugusto** [comment]
@deltragon thanks a lot for the link, that clears up a lot! I'm closing the issue since my question was answered.

**Comment by deltragon** [comment]
@hackaugusto Note also that it is very easy to run miri in the playground (it's under tools in the top right): [snippet](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=21358174b5beac51df8d36c22748f159)
This might not report undefined behaviour about things that haven't been decided yet, but can help a lot when trying to answer "is this UB?". (Eg, here is [the same snippet but with String ](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=21358174b5beac51df8d36c22748f159), which miri (rightly) reports as UB.)

**Comment by RalfJung** [comment]
Also remember that all the statements about which of these has UB is relative to the current Vec internal implementation. That implementation can change in the future which can lead to more UB. Consult the docs to learn which of these aspects are actually a stable promise.

**Comment by saethlin** [comment]
> here is [the same snippet but with String](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=21358174b5beac51df8d36c22748f159)

This is the same link as the other link in your reply, and `String` doesn't have a `set_len`, so I'm not even sure what you're trying to point out here.

**Comment by deltragon** [comment]
@saethlin Sorry, this link was supposed to be [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d9e67cc658d70d7f45f6191fb3a80f1e).
I was just trying to point how for `Vec<String>`, dropping the previous (uninitialized) data can trigger UB when assigning to `&mut uninit`.
