### ISSUE TITLE
Function Pointers

### ISSUE THREAD

**Issue by ubsan** [rust-lang/unsafe-code-guidelines#41]
And how they work on an ABI level, and what you can do with them!

(This is mostly a reminder to myself to actually start working on this later)

**Comment by gnzlbg** [comment]
Is this fixed?

**Comment by RalfJung** [comment]
I think https://github.com/rust-lang/unsafe-code-guidelines/blob/master/reference/src/layout/function-pointers.md fixes this. @ubsan please reopen if it does not.
