### ISSUE TITLE
Decide on the validity of function pointers

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#440]
### We decide

that the validity invariant for function pointers is: they need to be non-null.

Transmuting any provenance-free non-null input to a function pointer is definitely allowed without causing immediate UB.
When and whether these function pointers can actually be invoked is a different question and not answered here.

We do *not* decide what happens when the input has provenance. This is tracked [here](https://github.com/rust-lang/unsafe-code-guidelines/issues/286). In particular, values such as `&0` (that have provenance) might or might not be legal to transmute to function pointers.

### Rationale

The non-null requirement is already out there since forever and plenty of code relies on `Option<fn()>` having a null niche, so that part is not up for debate any more.

We considered requiring function pointers to be aligned to some target-specific alignment. However, for all currently supported targets, that alignment would be 1. (Note that even on ARM, where functions have alignment requirements, the lowest bit is used to indicate Thumb mode. So while functions are aligned, function pointers are not.) Furthermore, C clearly allows casting 0 to function pointers; it will be hard to argue that casting 1 or -1 to a function pointer is UB in C, so a target that makes alignment requirements for function pointers a validity concern is likely to be incompatible with C. Common practice conforms this: for instance, 1 is a [common value for `SIG_IGN`](https://github.com/rust-lang/libc/blob/28ab9b9e7bd04a5c5aca3f4d78583214f63d4002/src/unix/mod.rs#L213) which is cast to a function pointer to be stored in the `sa_handler` field of `sigaction` -- and while a new target could of course pick a higher-aligned value for `SIG_IGN`, there is likely more C code out there using various sentinel values. SQLite [uses `-1` as a sentinel](https://www.sqlite.org/c3ref/c_static.html). Even Rust code using 1 as a sentinel function pointer [has been spotted in the wild](https://github.com/rust-lang/unsafe-code-guidelines/issues/72#issuecomment-1025217996).

### Examples

The following pieces of code cause UB (as in, the UB arises when executing the code, not just potentially later):
```rust
let _val: fn() = MaybeUninit::uninit().assume_init();
```
```rust
let _val: fn() = mem::transmute(0usize);
```

The following piece of code is well-defined:
```rust
let val: fn() = mem::transmute(1usize);
// Note that safe code can cause UB with `val`!
// This operation is not sound, but it is well-defined.
// It violates only the safety invariant of `fn()`,
// not its validity invariant.
```

The following is *not decided* by this FCP:
```rust
let ptr = &0i32;
let ptr_to_ptr = addr_of!(ptr).cast::<usize>();
ptr_to_ptr.cast::<fn()>().read(); // pointer-to-fnptr transmutation -- UB or not?
```

The following functions are *sound* (as in, safe code invoking these functions can never have UB):
```rust
fn to_fn_then_discard(x: usize) {
  if x == 0 { return; }
  let f: fn() = unsafe { mem::transmute(x) };
  // Calling `f` would be very unsound, but just creating this pointer and then never using it is fine.
  drop(f);
}
```

### Prior discussion

- https://github.com/rust-lang/unsafe-code-guidelines/issues/72
- https://github.com/rust-lang/unsafe-code-guidelines/issues/81

**Comment by CAD97** [comment]
While I did make the argument to not bundle this with the other simple validity, I have no concerns with this actually being the validity requirement for function pointers. Even in the mentioned case where ABI expects function pointers to be aligned (say, to pack bool arguments as logically part of the ABI rather than part of the pointer), this can be made to be a requirement of the ABI rather than directly of function pointer layout.

**Comment by comex** [comment]
> ```rust
> let _val: i32 = MaybeUninit::uninit().assume_init();
> ```

Is `i32` here supposed to be `fn()`?  As-is, it is UB but doesn’t seem relevant to the topic.

**Comment by RalfJung** [comment]
> > ```rust
> > let _val: i32 = MaybeUninit::uninit().assume_init();
> > ```
> 
> Is `i32` here supposed to be `fn()`? As-is, it is UB but doesn’t seem relevant to the topic.

Oops, copy-paste error. Thanks, fixed.

**Comment by RalfJung** [comment]
Now again with T-opsem label...
@rfcbot merge

**Comment by RalfJung** [comment]
Added to our FCP list of "decisions we made", so the issue can be closed.
