### ISSUE TITLE
Is it sound to split an `UnsafeCell` into multiple `UnsafeCell`s?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/unsafe-code-guidelines#458]
Miri doesn't complain about the following code, but is this guaranteed to be sound?

```rust
fn main() {
    let x = UnsafeCell::new([0u8; 2]);
    let x = &x;
    let x_ptr: *const UnsafeCell<[u8; 2]> = x;
    let y_ptr = x_ptr as *const [UnsafeCell<u8>; 2];
    let _y = unsafe { &*y_ptr };
}
```

I read https://github.com/rust-lang/unsafe-code-guidelines/issues/451#issuecomment-1698570619 as implying this is intended to be sound, but I wanted to double-check.

**Comment by RalfJung** [comment]
Isn't this basically https://doc.rust-lang.org/nightly/std/cell/struct.Cell.html#method.as_array_of_cells ?

**Comment by RalfJung** [comment]
Also I'd say this is a duplicate of https://github.com/rust-lang/unsafe-code-guidelines/issues/451; projection to struct fields and array "fields" should behave the same.

**Comment by joshlf** [comment]
Sounds good, that's what I figured. Thanks!
