### ISSUE TITLE
Layout of DSTs with over-alignment?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/unsafe-code-guidelines#460]
What guarantees are provided regarding trailing padding at the end of a DST?

Experimentally, it seems that the current behavior for both `repr(rust)` and `repr(C)` DSTs is that padding will be added after the trailing field as required by the outer type's alignment. The amount of padding is computed dynamically - that is, the amount of padding is a function of the number of elements in the trailing slice.

This behavior is consistent with the behavior which is [documented in the reference](https://doc.rust-lang.org/reference/type-layout.html) if we interpret its language as applying to DSTs as well as to sized types. E.g., if we read the section on [`repr(C)` structs](https://doc.rust-lang.org/reference/type-layout.html#reprc-structs) as describing dynamic sizes, offsets, and padding locations, it implies that we should expect this behavior. However, since these concepts are usually discussed in a context in which 
they are static, compile-time properties, it's not obvious to me that the authors intended for the text to describe DSTs.

What guarantees are provided for the layout of DSTs? It would be helpful to know the answer for all representations including `repr(rust)`. While, for sized types, `repr(rust)` doesn't guarantee much, it does provide a few basic guarantees that are foundational for a lot of unsafe code. Being able to rely on similar guarantees for DSTs would be a big deal.

## Experiments

This code tests Rust's current behavior regarding DSTs whose alignment is larger than the size of the trailing slice element.

```rust
#[repr(C)]
struct Foo<T: ?Sized> {
    a: [u32; 0],
    t: T,
}

macro_rules! print_meta {
    ($($t:ty),*) => {
    println!("\tbase_size\tbase_align\tone_size\tone_align\tthree_size\tthree_align");
        $({
            let empty = NonNull::slice_from_raw_parts(NonNull::<()>::dangling(), 0).as_ptr() as *mut Foo<$t>;
            let with_one_elem = NonNull::slice_from_raw_parts(NonNull::<()>::dangling(), 1).as_ptr() as *mut Foo<$t>;
            let with_three_elems = NonNull::slice_from_raw_parts(NonNull::<()>::dangling(), 3).as_ptr() as *mut Foo<$t>;

            let base_size = mem::size_of_val_raw(empty);
            let base_align = mem::align_of_val_raw(empty);
            let one_size = mem::size_of_val_raw(with_one_elem);
            let one_align = mem::align_of_val_raw(with_one_elem);
            let three_size = mem::size_of_val_raw(with_three_elems);
            let three_align = mem::align_of_val_raw(with_three_elems);

            println!("{}\t{base_size}\t\t{base_align}\t\t{one_size}\t\t{one_align}\t\t{three_size}\t\t{three_align}", stringify!($t));
        })*
    }
}

unsafe {
    print_meta!((), u8, u16, [()], [u8], [u16]);
};
```

This code outputs the following, including after removing the `#[repr(C)]` annotation:

```text
	base_size	base_align	one_size	one_align	three_size	three_align
()	0		4		0		4		0		4
u8	4		4		4		4		4		4
u16	4		4		4		4		4		4
[()]	0		4		0		4		0		4
[u8]	0		4		4		4		4		4
[u16]	0		4		4		4		8		4
```

The behavior for a similar `repr(packed)` struct is also as expected:

```rust
#[repr(packed)]
struct Foo<T: ?Sized> {
    a: [u32; 0],
    t: mem::ManuallyDrop<T>,
}
```

```text
	base_size	base_align	one_size	one_align	three_size	three_align
()	0		1		0		1		0		1
u8	1		1		1		1		1		1
u16	2		1		2		1		2		1
[()]	0		1		0		1		0		1
[u8]	0		1		1		1		3		1
[u16]	0		1		2		1		6		1
```

**Comment by RalfJung** [comment]
I'm not sure what kinds of guarantees you are looking for.

For instance, I am fairly sure that we guarantee that `size_of_val` is a multiple of `align_of_val` for the same value, similar to how we have the same guarantee for the static size/align of sized types. Is that what you mean? Which other other concrete properties are you hoping for?

**Comment by joshlf** [comment]
Sorry for completely dropping the ball on responding to this! We ended up figuring everything out.
