### ISSUE TITLE
What are the contents of the return place upon unwinding?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#468]
This question came up [here](https://github.com/rust-lang/rust/pull/116454#discussion_r1349486011). When a function is called, performs some writes to its return local, and then unwinds -- what do we guarantee about the contents of the return place (i.e., the place given by the caller to store the return value in)?

The semantics currently implemented in Miri are: when the function is called, the return place is de-initialized. The function locally creates a fresh place to back its return local. Writes to the return local only affect that temporary place. Upon unwinding, no copying of a return value happens, so the return place remains fully uninitialized.

Those seem like reasonable semantics. We effectively do not guarantee anything about that place when unwinding happened. Any objections/discussion or shall we move to FCP directly?

**Comment by bjorn3** [comment]
I agree that the semantics implemented in miri are reasonable. I don't think it is observable in the user facing language though, only in MIR.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/miri/pull/3114 adds a test in Miri.

I'll close this then as "not controversial" and "does not even apply to surface language".
