### ISSUE TITLE
Provenance for zero-sized accesses?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/unsafe-code-guidelines#490]
Is provenance required in order to perform zero-sized accesses? Following up on https://github.com/rust-lang/rust/pull/116677#issuecomment-1942566795, I understand that it is sound (e.g. per the [`ptr` module docs](https://doc.rust-lang.org/std/ptr/index.html#safety)) to perform a zero-sized load or store using a pointer derived from any non-zero integer literal. Since integers do not have provenance, this implies that zero-sized accesses do not require valid provenance. Is that correct?

**Comment by digama0** [comment]
I believe this is covered by the FCP on zero-sized accesses #472 (which was approved but IIRC still has some implementation work to avoid LLVM miscompilations). All zero-sized accesses are allowed, including those with invalid provenance or no provenance. The ptr module docs have an exception for provenance to deallocated memory, but hopefully this can be removed at some point.

**Comment by RalfJung** [comment]
The status quo is that the zero-sized accesses require either valid provenance or no provenance.

https://github.com/rust-lang/rust/issues/117945 tracks changing this to allowing any provenance.
