### ISSUE TITLE
Dead variant removal in `#[repr(C)]` enums

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/unsafe-code-guidelines#500]
Consider this enum:

```rust
#[repr(C)]
enum Fun<T> {
    Fun(T),
    // maybe some other variants here
}
```

For unsafe code it could be useful to assume that `Fun<T>` is layout-compatible with `Fun<MaybeUninit<T>>` for any choice of `T`. That’s not currently the case: if `T` is uninhabited, `Fun<T>` would be zero-sized (or, more generally, the `::Fun` variant will not affect enum size), but `Fun<MaybeUninit<T>>` wouldn’t.

Reference currently [documents](https://doc.rust-lang.org/reference/type-layout.html#reprc-enums-with-fields) the above enum as being rough equivalent to something like

```rust
#[repr(C)]
enum FunDiscriminant {
    Fun,
}

#[repr(C)]
union FunData<T> {
    fun: T,
}

#[repr(C)]
struct Fun<T> {
    discriminant: FunDiscriminant,
    data: FunData<T>,
}
```

That doesn’t hold for uninhabited types: this “desugaring” preserves the invariant above.

I think we should do one of the following:
1. Either dead variant removal should be disabled for `#[repr(C)]` enums;
2. or it should be documented in the reference (I can write the patch if this option is selected).

Related: #443
Playground demonstrating the issue: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d2995ff99cea9c2e60d28cbf0f970176

**Comment by RalfJung** [comment]
It's interesting what happens when you remove the `repr(C)` from `FunDiscriminant`:
```
[src/main.rs:29:5] std::mem::size_of::<Fun<Void>>() = 0
[src/main.rs:30:5] std::mem::size_of::<Fun<std::mem::MaybeUninit<Void>>>() = 4
[src/main.rs:31:5] std::mem::size_of::<desugared::Fun<Void>>() = 0
[src/main.rs:32:5] std::mem::size_of::<desugared::Fun<std::mem::MaybeUninit<Void>>>() = 0
```
That's more what I expected: single-variant enums can have a zero-sized discriminant.

Also interestingly, zero-variant enums with `repr(C)` are rejected.

---

My first reaction is that this is a bug in rustc, we shouldn't do dead variant removal on `repr(C)` enums.

**Comment by chorman0773** [comment]
I agree with that. Even if the variant is uninhabited, we guarantee that there's a target-dependant discriminant field in the layout of a `repr(C)` enum.

**Comment by GoldsteinE** [comment]
Assuming that’s a rustc bug, I sent a patch that fixes it.

**Comment by GoldsteinE** [comment]
The fix is stable now, so I think this could be closed.
