### ISSUE TITLE
What are the guarantees over ZST pointers

### ISSUE THREAD

**Issue by celinval** [rust-lang/unsafe-code-guidelines#503]
Hi, we've been trying to understand what's the correct way to model ZST pointers. What is UB and what has well defined behavior. 

1. Does a ZST pointer have provenance?
2. Does ZST pointer identity hold?
3. If it point to a ZST field in a structure, will it always be inbounds?
4. Will the address of a static ZST always fall in the memory section of statics? Will the address of a local ZST always point to a location in the stack frame?
5. Should a ZST pointer comparison take provenance into account or just the address?

Thanks!

**Comment by Lokathor** [comment]
1) I think you mean "provenance", and yes technically they do.
2) Not sure what you're asking. `a == a` will be true for a ZST pointer, if that's what you mean.
3) A pointer to a field of a struct will be inbounds of the full struct, yeah.
4) This is not guaranteed in any way. In fact, some people would like this to specifically not be the case so that ZST address values can be const folded.
5) Pointer comparison doesn't compare provenance, just the address (and possibly more with a DST, but we'll ignore that for now).

**Comment by chorman0773** [comment]
For almost all purposes related to provenance, a pointer to a ZST is not distinct from a pointer to another type.
There are additional guarantees in terms of what operations are valid, when that operation is done with zero size. For example, memory accesses of zero size are trivially valid when well-aligned.

**Comment by celinval** [comment]
> 1. I think you mean "provenance", and yes technically they do.
> 
>     2. Not sure what you're asking. `a == a` will be true for a ZST pointer, if that's what you mean.
> 
>     3. A pointer to a field of a struct will be inbounds of the full struct, yeah.
> 
>     4. This is not guaranteed in any way. In fact, some people would like this to specifically not be the case so that ZST address values can be const folded.
> 
>     5. Pointer comparison doesn't compare provenance, just the address (and possibly more with a DST, but we'll ignore that for now).

Sorry, my phone keeps auto correcting provenance for some reason

**Comment by celinval** [comment]
>     5. Pointer comparison doesn't compare provenance, just the address (and possibly more with a DST, but we'll ignore that for now).

I thought that was still up for debate in this issue: https://github.com/rust-lang/unsafe-code-guidelines/issues/239

**Comment by RalfJung** [comment]
For further information on provenance, see [the RFC](https://rust-lang.github.io/rfcs/3559-rust-has-provenance.html). The pointee type and being a reference vs a raw pointer makes no difference for provenance.

> I thought that was still up for debate from reading this issue: https://github.com/rust-lang/unsafe-code-guidelines/issues/239

Yes, we haven't made an official t-lang decision on this. But at this point it seems unlikely that provenance will affect pointer comparison.

On today's Rust, provenance does not affect pointer comparison.

> Will the address of a static ZST always fall in the memory section of statics? Will the address of a local ZST always point to a location in the stack frame?

The Rust specification does not have a notion of memory sections for statics or stack frames. All allocated objects are placed at arbitrary locations in memory and there is no guarantee whatsoever that stack allocations are in "the stack" or `Box` allocations are on "the heap".

---

I think this answers all questions, or would you like further clarification?

**Comment by tautschnig** [comment]
> The Rust specification does not have a notion of memory sections for statics or stack frames. All allocated objects are placed at arbitrary locations in memory and there is no guarantee whatsoever that stack allocations are in "the stack" or Box allocations are on "the heap".

https://doc.rust-lang.org/reference/variables.html says that "A local variable (or stack-local allocation) holds a value directly, allocated within the stack's memory." (And https://doc.rust-lang.org/reference/memory-allocation-and-lifetime.html says something about Box and heap, but indeed does not promise that all Box allocations would be on the heap.)

**Comment by celinval** [comment]
> For example, memory accesses of zero size are trivially valid when well-aligned.

I think that would be a simple way to go about it, since these are no-op, but if I understand it correctly, a zero-size access is invalid if the pointer points to a deallocated memory, correct? I'm assuming that's because of provenance.

I am curious if provenance is also taken into account if the pointer is out-of-bounds of the original object? Would a zero-size access be valid in out-of-bounds pointers?

**Comment by RalfJung** [comment]
> if I understand it correctly, a zero-size access is invalid if the pointer points to a deallocated memory, correct? I'm assuming that's because of provenance.

This used to be the case but we decided to change it and allow more code. See https://github.com/rust-lang/rust/issues/117945. Once that is fully implemented, zero-sized accesses ignore provenance.

**Comment by celinval** [comment]
I think this answers all my questions. Thank you!

**Comment by RalfJung** [comment]
Sure, happy to help. :)
