### ISSUE TITLE
Decide on validity for metadata of wide pointer/reference with slice tail

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#510]
This is a part of https://github.com/rust-lang/unsafe-code-guidelines/issues/166, needed to unblock https://github.com/rust-lang/rust/pull/121965 and https://github.com/rust-lang/rust/pull/116542.

A type `T` has "slice tail" if it is unsized and its last field (recursively descending through structs/tuples) is of the shape `[U]`. For such types, we say that
1. The validity invariant of the metadata part of `*const T` and `*mut T` is exactly the same as that of `usize`.
2. The validity invariant of the metadata part of `&T` and `&mut T` is that of `usize` with the further constraint that the total size of a `T` with that metadata must not exceed `isize::MAX`.

The representation relation is otherwise that of an integer (so, what happens when the metadata has provenance matches what happens when a `usize` has provenance -- we haven't decided what exactly that will be, but it should be consistent).

Rationale:
1. We don't have a choice here, as [`slice_from_raw_parts`](https://doc.rust-lang.org/nightly/std/ptr/fn.slice_from_raw_parts.html) is a stable safe function that can construct a wide raw slice pointer with an arbitrary value for its metadata.
2. This will allow us to [add niches](https://github.com/rust-lang/rust/pull/116542) in slice metadata.

I think the only possibly controversial point here is that the validity invariant is not the same for metadata of `*const [U]`  and `&[U]`. However, given that the validity invariant is already not the same for the data part of these (obviously), maybe that's not so surprising?

I am not including vtables in this as I think we have more discussing to do there.

@rust-lang/opsem  what do you think? Any objections to moving to FCP swiftly?

**Comment by CAD97** [comment]
No objections here and seconded that this is good to FCP ~~yesterday~~. This may have some interesting implications w.r.t. `ptr_metadata` (`&T` needs to logically be different from just `(&_, <T as Pointee>::Metadata)`), but that doesn't seem like it'd be a fundamental issue.

Most cases that require validity will also retag the reference (thus require dereferencability which implies the same metadata constraints), with the exception being `ManuallyDrop` IIRC. While the difference existing could be a bit surprising, I don't expect it to cause issues in practice.

**Comment by workingjubilee** [comment]
> Rationale:
> 
>     1. We don't have a choice here, as [`slice_from_raw_parts`](https://doc.rust-lang.org/nightly/std/ptr/fn.slice_from_raw_parts.html) is a stable safe function that can construct a wide raw slice pointer with an arbitrary value for its metadata.
>

The function could always do a conversion to another metadata format, I suppose.

>     2. This will allow us to [add niches](https://github.com/rust-lang/rust/pull/116542) in slice metadata.
> 

But this seems justification enough.

As far as the difference of the validity invariant, I think that it is fine: `&Tailed` implies that for the metadata size, that data is legible, right? It seems pointers having no equivalent validity invariant necessarily follows from the pointer not carrying an assertion that the pointee is valid and leaving that at the moment of creation. That's basically the same reason why `*const T` has no niches but `&T` does.

**Comment by RalfJung** [comment]
> As far as the difference of the validity invariant, I think that it is fine: &Tailed implies that for the metadata size, that data is legible, right? It seems pointers having no equivalent validity invariant on the metadata part necessarily follows from the pointer not carrying an assertion that the pointee is valid, leaving that at the moment of creation. That's basically the same reason why *const T has no niches but &T does.

Kind of... there's the point @CAD97 mentioned about `MaybeDangling<&SliceTailed>` (assuming an implementation of https://github.com/rust-lang/rfcs/pull/3336), which cancels out `dereferenceable` but preserves the niche.

**Comment by workingjubilee** [comment]
Like a very... interesting... spelling of `NonNull`.

**Comment by RalfJung** [comment]
Under the above semantics, `MaybeDangling<&SliceTailed>` would spell: not null, well-aligned, and the metadata is such that the entire type fits in `isize::MAX`.

**Comment by RalfJung** [comment]
> No objections here and seconded that this is good to FCP yesterday

Let's get the show started, then.
@rfcbot fcp merge

**Comment by workingjubilee** [comment]
...does rfcbot not listen to this repo?

**Comment by RalfJung** [comment]
IIRC it doesn't have a hook but instead just checks every few hours or so.

**Comment by RalfJung** [comment]
However, I thought it did the check every full hour. Maybe the command is wrong. I took it from the docs, but last time I used a different command...
@rfcbot merge

**Comment by saethlin** [comment]
The only crate I'm aware of that tries to violate this requirement is https://crates.io/crates/deepmesa-collections, and that crate tries to do so by calling `slice::from_raw_parts`, which now contains a runtime UB check. Thus the crate's test suite does not pass on stable and it has no published dependents (aside from its own workspace members).

**Comment by saethlin** [comment]
rfcbot is unchecking our boxes.

**Comment by workingjubilee** [comment]
I have filed https://github.com/deepmesa/deepmesa-rs/issues/14 as a courtesy to the author and a notification to anyone who inspects the repo.

**Comment by CAD97** [comment]
let's try

@rfcbot reviewed

**Comment by RalfJung** [comment]
> let's try
> 
> @rfcbot reviewed

Yeah, then at least we can see in the log who approved, even if rfcbot unchecks boxes again

**Comment by saethlin** [comment]
@rfcbot reviewed

**Comment by joshlf** [comment]
> 2\. The validity invariant of the metadata part of `&T` and `&mut T` is that of `usize` with the further constraint that the total size of a `T` with that metadata must not exceed `isize::MAX`.

Given that we want to hold open the possibility that the validity invariant of `&T`/`&mut T` is that its referent is bit-valid, do we also want to hold open the possibility that the validity invariant of the *metadata part of* `&T`/`&mut T` also includes something about the entire referent being inside a single allocation, the reference having valid provenance for its entire referent, etc etc? In other words, are there other constraints we might want to add in the future, and does saying that these are the exact validity invariants preclude us from adding those in the future?

**Comment by RalfJung** [comment]
> Given that we want to hold open the possibility that the validity invariants of &T/&mut T include that its referent is bit-valid, do we also want to hold open the possibility that the validity invariants of the metadata part of &T/&mut T also include something about the entire referent being inside a single allocation, the reference having valid provenance for its entire referent, etc etc?

All of this applies to sized and unsized types equally, so I don't think it is part of this discussion.

**Comment by RalfJung** [comment]
Great, thanks all. :) The issue can be closed then.

**Comment by RalfJung** [comment]
Reference PR: https://github.com/rust-lang/reference/pull/1499
