### ISSUE TITLE
Stacked Borrows: Handling of two-phase borrows

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#85]
Basically just a reference to https://github.com/rust-lang/rust/issues/56254, so that we have all Stacked Borrows issues in one place.

Since that issue was created, I decided to basically give up on two-phase borrows in Stacked Borrows, and treat them like raw pointers. That is the only way I found to accept the safe code allowed by two-phase borrows.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/miri/issues/1878 contains an interesting example of code that we really ought to reject, but currently accept due to two-phase borrows.

**Comment by RalfJung** [comment]
FWIW I still think it would be useful to know that the `&mut` we get as a function argument is *not* "delayed". That is probably needed for some optimizations.

**Comment by CAD97** [comment]
I agree that this seems very reasonable, potentially as part of the protectors also introduced by the function boundary.

**Comment by RalfJung** [comment]
Closing as resolved by tree borrows.
